# SonarCloud Project Information
sonar.projectKey=chanidu-org_information-security-project
sonar.organization=chanidu-org
sonar.branch.name=main

# Project Info
sonar.projectName=Information Security Project
sonar.projectVersion=1.0

# Source Code
sonar.sources=.

# Python Settings
sonar.language=py
sonar.sourceEncoding=UTF-8

# Exclude unnecessary files
sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**,.venv/**,tests/**